fileVersion: 1
id: "19"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: SHRUTHI_5_4QA
    schema: QA_5_4
name: New Environment
type: Environment
