fileVersion: 1
id: "21"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: QA_DB
    schema: QA_DB_SCHEMA
name: New Environment
type: Environment
