@id("d46bd958-1b9c-4134-93ab-b38270341d49")
@nodeType("49")
SELECT
     "P_PARTKEY" AS "P_PARTKEY",
     "P_NAME" AS "P_NAME",
     "P_MFGR" AS "P_MFGR",
     "P_BRAND" AS "P_BRAND",
     "P_TYPE" AS "P_TYPE",
     "P_SIZE" AS "P_SIZE",
     "P_CONTAINER" AS "P_CONTAINER",
     "P_RETAILPRICE" AS "P_RETAILPRICE",
     "P_COMMENT" AS "P_COMMENT"
FROM {{ ref('WORK', 'STG_PART') }} "STG_PART"